/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QPushButton *cartPsip;
    QPushButton *initialize;
    QLineEdit *cycleTheta1;
    QPushButton *record;
    QLabel *label_5;
    QPushButton *cartThetam;
    QLabel *label_14;
    QLineEdit *cycleZ1;
    QLabel *label_19;
    QLabel *label_4;
    QLabel *label_43;
    QTextBrowser *theta2;
    QPushButton *clear;
    QPushButton *cartPhip;
    QLabel *label_28;
    QPushButton *cartZm;
    QPushButton *cartPhim;
    QLabel *label_39;
    QLineEdit *linePhi;
    QTextBrowser *cartPhi;
    QLabel *label_26;
    QTextBrowser *theta1;
    QLabel *label_12;
    QPushButton *theta1p;
    QTextBrowser *cartZ;
    QLabel *label_9;
    QLabel *label_25;
    QLabel *label_29;
    QTextBrowser *cartY;
    QPushButton *theta3m;
    QLineEdit *cyclePhi2;
    QLabel *label_45;
    QLineEdit *cartV;
    QPushButton *theta3p;
    QLineEdit *cyclePhi1;
    QLabel *label_3;
    QLineEdit *cyclePsi1;
    QPushButton *cartPsim;
    QPushButton *goToZero;
    QTextBrowser *cartPsi;
    QPushButton *cartXm;
    QLabel *label_42;
    QPushButton *theta6m;
    QLineEdit *cycleX1;
    QLabel *label;
    QTextBrowser *cartTheta;
    QPushButton *theta2m;
    QLabel *label_2;
    QLabel *label_38;
    QLineEdit *lineZ;
    QLineEdit *cycleY2;
    QPushButton *cycleRun;
    QLineEdit *lineTheta;
    QTextBrowser *cartX;
    QLineEdit *cartCNT;
    QLineEdit *cycleV;
    QTextBrowser *systermState;
    QLabel *label_7;
    QLabel *label_36;
    QPushButton *theta1m;
    QPushButton *theta4m;
    QLineEdit *lineX;
    QLabel *label_21;
    QLabel *label_15;
    QLineEdit *lineY;
    QLabel *label_35;
    QLineEdit *cycleZ2;
    QPushButton *theta6p;
    QLabel *label_13;
    QPushButton *cartYp;
    QPushButton *cartRun;
    QPushButton *cartThetap;
    QLineEdit *lineV;
    QLabel *label_27;
    QLabel *label_20;
    QLineEdit *cyclePsi2;
    QLabel *label_31;
    QLabel *label_40;
    QLabel *label_8;
    QLabel *label_24;
    QPushButton *theta2p;
    QLabel *label_17;
    QPushButton *cartZp;
    QPushButton *cartXp;
    QLabel *label_16;
    QLabel *label_6;
    QPushButton *theta4p;
    QLabel *label_44;
    QLabel *label_22;
    QPushButton *theta5m;
    QLabel *label_23;
    QLineEdit *cycleTheta2;
    QTextBrowser *cartDisplay;
    QTextBrowser *theta5;
    QPushButton *theta5p;
    QTextBrowser *theta4;
    QLabel *label_11;
    QTextBrowser *theta3;
    QLineEdit *linePsi;
    QLineEdit *cycleY1;
    QPushButton *cartYm;
    QTextBrowser *theta6;
    QPushButton *clearSysState;
    QPushButton *lineRun;
    QLabel *label_32;
    QLabel *label_18;
    QLabel *label_41;
    QLineEdit *cycleX2;
    QLabel *label_33;
    QLabel *label_30;
    QLabel *label_10;
    QPushButton *connect;
    QPushButton *close;
    QLabel *label_34;
    QPushButton *enable;
    QPushButton *stop;
    QLabel *label_37;
    QComboBox *CANCom;
    QLabel *label_46;
    QComboBox *baundRate;
    QTextBrowser *systermState_2;
    QTextBrowser *systermState_3;
    QTextBrowser *systermState_4;
    QTextBrowser *systermState_5;
    QTextBrowser *systermState_6;
    QTextBrowser *systermState_7;
    QTextBrowser *systermState_8;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(988, 921);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        cartPsip = new QPushButton(centralWidget);
        cartPsip->setObjectName(QString::fromUtf8("cartPsip"));
        cartPsip->setGeometry(QRect(480, 410, 31, 24));
        initialize = new QPushButton(centralWidget);
        initialize->setObjectName(QString::fromUtf8("initialize"));
        initialize->setGeometry(QRect(60, 50, 91, 41));
        cycleTheta1 = new QLineEdit(centralWidget);
        cycleTheta1->setObjectName(QString::fromUtf8("cycleTheta1"));
        cycleTheta1->setGeometry(QRect(550, 760, 71, 31));
        record = new QPushButton(centralWidget);
        record->setObjectName(QString::fromUtf8("record"));
        record->setGeometry(QRect(300, 480, 93, 41));
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(380, 190, 72, 15));
        label_5->setAlignment(Qt::AlignCenter);
        cartThetam = new QPushButton(centralWidget);
        cartThetam->setObjectName(QString::fromUtf8("cartThetam"));
        cartThetam->setGeometry(QRect(620, 410, 31, 24));
        label_14 = new QLabel(centralWidget);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(380, 350, 72, 15));
        label_14->setAlignment(Qt::AlignCenter);
        cycleZ1 = new QLineEdit(centralWidget);
        cycleZ1->setObjectName(QString::fromUtf8("cycleZ1"));
        cycleZ1->setGeometry(QRect(350, 760, 71, 31));
        label_19 = new QLabel(centralWidget);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(110, 561, 72, 20));
        label_19->setAlignment(Qt::AlignCenter);
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(280, 190, 72, 15));
        label_4->setAlignment(Qt::AlignCenter);
        label_43 = new QLabel(centralWidget);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(250, 790, 72, 15));
        label_43->setAlignment(Qt::AlignCenter);
        theta2 = new QTextBrowser(centralWidget);
        theta2->setObjectName(QString::fromUtf8("theta2"));
        theta2->setGeometry(QRect(280, 210, 71, 31));
        clear = new QPushButton(centralWidget);
        clear->setObjectName(QString::fromUtf8("clear"));
        clear->setGeometry(QRect(400, 480, 93, 41));
        cartPhip = new QPushButton(centralWidget);
        cartPhip->setObjectName(QString::fromUtf8("cartPhip"));
        cartPhip->setGeometry(QRect(680, 410, 31, 24));
        label_28 = new QLabel(centralWidget);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(70, 460, 151, 31));
        QFont font;
        font.setFamily(QString::fromUtf8("\351\273\221\344\275\223"));
        font.setPointSize(12);
        label_28->setFont(font);
        cartZm = new QPushButton(centralWidget);
        cartZm->setObjectName(QString::fromUtf8("cartZm"));
        cartZm->setGeometry(QRect(420, 410, 31, 24));
        cartPhim = new QPushButton(centralWidget);
        cartPhim->setObjectName(QString::fromUtf8("cartPhim"));
        cartPhim->setGeometry(QRect(720, 410, 31, 24));
        label_39 = new QLabel(centralWidget);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(450, 790, 72, 21));
        label_39->setAlignment(Qt::AlignCenter);
        linePhi = new QLineEdit(centralWidget);
        linePhi->setObjectName(QString::fromUtf8("linePhi"));
        linePhi->setGeometry(QRect(650, 670, 71, 31));
        cartPhi = new QTextBrowser(centralWidget);
        cartPhi->setObjectName(QString::fromUtf8("cartPhi"));
        cartPhi->setGeometry(QRect(680, 370, 71, 31));
        label_26 = new QLabel(centralWidget);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(80, 764, 72, 21));
        theta1 = new QTextBrowser(centralWidget);
        theta1->setObjectName(QString::fromUtf8("theta1"));
        theta1->setGeometry(QRect(180, 210, 71, 31));
        label_12 = new QLabel(centralWidget);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(180, 350, 72, 15));
        label_12->setAlignment(Qt::AlignCenter);
        theta1p = new QPushButton(centralWidget);
        theta1p->setObjectName(QString::fromUtf8("theta1p"));
        theta1p->setGeometry(QRect(180, 260, 31, 24));
        cartZ = new QTextBrowser(centralWidget);
        cartZ->setObjectName(QString::fromUtf8("cartZ"));
        cartZ->setGeometry(QRect(380, 370, 71, 31));
        label_9 = new QLabel(centralWidget);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(140, 260, 31, 21));
        label_25 = new QLabel(centralWidget);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(80, 710, 151, 31));
        label_25->setFont(font);
        label_29 = new QLabel(centralWidget);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(150, 650, 72, 15));
        label_29->setAlignment(Qt::AlignCenter);
        cartY = new QTextBrowser(centralWidget);
        cartY->setObjectName(QString::fromUtf8("cartY"));
        cartY->setGeometry(QRect(280, 370, 71, 31));
        theta3m = new QPushButton(centralWidget);
        theta3m->setObjectName(QString::fromUtf8("theta3m"));
        theta3m->setGeometry(QRect(420, 260, 31, 24));
        cyclePhi2 = new QLineEdit(centralWidget);
        cyclePhi2->setObjectName(QString::fromUtf8("cyclePhi2"));
        cyclePhi2->setGeometry(QRect(650, 810, 71, 31));
        label_45 = new QLabel(centralWidget);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(500, 10, 72, 20));
        label_45->setAlignment(Qt::AlignCenter);
        cartV = new QLineEdit(centralWidget);
        cartV->setObjectName(QString::fromUtf8("cartV"));
        cartV->setGeometry(QRect(110, 530, 71, 31));
        theta3p = new QPushButton(centralWidget);
        theta3p->setObjectName(QString::fromUtf8("theta3p"));
        theta3p->setGeometry(QRect(380, 260, 31, 24));
        cyclePhi1 = new QLineEdit(centralWidget);
        cyclePhi1->setObjectName(QString::fromUtf8("cyclePhi1"));
        cyclePhi1->setGeometry(QRect(650, 760, 71, 31));
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(180, 190, 71, 16));
        label_3->setAlignment(Qt::AlignCenter);
        label_3->setMargin(0);
        cyclePsi1 = new QLineEdit(centralWidget);
        cyclePsi1->setObjectName(QString::fromUtf8("cyclePsi1"));
        cyclePsi1->setGeometry(QRect(450, 760, 71, 31));
        cartPsim = new QPushButton(centralWidget);
        cartPsim->setObjectName(QString::fromUtf8("cartPsim"));
        cartPsim->setGeometry(QRect(520, 410, 31, 24));
        goToZero = new QPushButton(centralWidget);
        goToZero->setObjectName(QString::fromUtf8("goToZero"));
        goToZero->setGeometry(QRect(60, 100, 91, 41));
        cartPsi = new QTextBrowser(centralWidget);
        cartPsi->setObjectName(QString::fromUtf8("cartPsi"));
        cartPsi->setGeometry(QRect(480, 370, 71, 31));
        cartXm = new QPushButton(centralWidget);
        cartXm->setObjectName(QString::fromUtf8("cartXm"));
        cartXm->setGeometry(QRect(220, 410, 31, 24));
        label_42 = new QLabel(centralWidget);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(550, 790, 72, 21));
        label_42->setAlignment(Qt::AlignCenter);
        theta6m = new QPushButton(centralWidget);
        theta6m->setObjectName(QString::fromUtf8("theta6m"));
        theta6m->setGeometry(QRect(720, 260, 31, 24));
        cycleX1 = new QLineEdit(centralWidget);
        cycleX1->setObjectName(QString::fromUtf8("cycleX1"));
        cycleX1->setGeometry(QRect(150, 760, 71, 31));
        label = new QLabel(centralWidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(70, 150, 131, 31));
        label->setFont(font);
        cartTheta = new QTextBrowser(centralWidget);
        cartTheta->setObjectName(QString::fromUtf8("cartTheta"));
        cartTheta->setGeometry(QRect(580, 370, 71, 31));
        theta2m = new QPushButton(centralWidget);
        theta2m->setObjectName(QString::fromUtf8("theta2m"));
        theta2m->setGeometry(QRect(320, 260, 31, 24));
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(140, 214, 72, 21));
        label_38 = new QLabel(centralWidget);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(150, 790, 72, 15));
        label_38->setAlignment(Qt::AlignCenter);
        lineZ = new QLineEdit(centralWidget);
        lineZ->setObjectName(QString::fromUtf8("lineZ"));
        lineZ->setGeometry(QRect(350, 670, 71, 31));
        cycleY2 = new QLineEdit(centralWidget);
        cycleY2->setObjectName(QString::fromUtf8("cycleY2"));
        cycleY2->setGeometry(QRect(250, 810, 71, 31));
        cycleRun = new QPushButton(centralWidget);
        cycleRun->setObjectName(QString::fromUtf8("cycleRun"));
        cycleRun->setGeometry(QRect(840, 780, 91, 41));
        lineTheta = new QLineEdit(centralWidget);
        lineTheta->setObjectName(QString::fromUtf8("lineTheta"));
        lineTheta->setGeometry(QRect(550, 670, 71, 31));
        cartX = new QTextBrowser(centralWidget);
        cartX->setObjectName(QString::fromUtf8("cartX"));
        cartX->setGeometry(QRect(180, 370, 71, 31));
        cartCNT = new QLineEdit(centralWidget);
        cartCNT->setObjectName(QString::fromUtf8("cartCNT"));
        cartCNT->setGeometry(QRect(210, 530, 71, 31));
        cycleV = new QLineEdit(centralWidget);
        cycleV->setObjectName(QString::fromUtf8("cycleV"));
        cycleV->setGeometry(QRect(750, 760, 71, 31));
        systermState = new QTextBrowser(centralWidget);
        systermState->setObjectName(QString::fromUtf8("systermState"));
        systermState->setGeometry(QRect(500, 30, 451, 121));
        systermState->setReadOnly(true);
        label_7 = new QLabel(centralWidget);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(580, 190, 72, 15));
        label_7->setAlignment(Qt::AlignCenter);
        label_36 = new QLabel(centralWidget);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(650, 790, 72, 21));
        label_36->setAlignment(Qt::AlignCenter);
        theta1m = new QPushButton(centralWidget);
        theta1m->setObjectName(QString::fromUtf8("theta1m"));
        theta1m->setGeometry(QRect(220, 260, 31, 24));
        theta4m = new QPushButton(centralWidget);
        theta4m->setObjectName(QString::fromUtf8("theta4m"));
        theta4m->setGeometry(QRect(520, 260, 31, 24));
        lineX = new QLineEdit(centralWidget);
        lineX->setObjectName(QString::fromUtf8("lineX"));
        lineX->setGeometry(QRect(150, 670, 71, 31));
        label_21 = new QLabel(centralWidget);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(550, 650, 72, 15));
        label_21->setAlignment(Qt::AlignCenter);
        label_15 = new QLabel(centralWidget);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(480, 350, 72, 15));
        label_15->setAlignment(Qt::AlignCenter);
        lineY = new QLineEdit(centralWidget);
        lineY->setObjectName(QString::fromUtf8("lineY"));
        lineY->setGeometry(QRect(250, 670, 71, 31));
        label_35 = new QLabel(centralWidget);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(750, 640, 72, 31));
        label_35->setAlignment(Qt::AlignCenter);
        cycleZ2 = new QLineEdit(centralWidget);
        cycleZ2->setObjectName(QString::fromUtf8("cycleZ2"));
        cycleZ2->setGeometry(QRect(350, 810, 71, 31));
        theta6p = new QPushButton(centralWidget);
        theta6p->setObjectName(QString::fromUtf8("theta6p"));
        theta6p->setGeometry(QRect(680, 260, 31, 24));
        label_13 = new QLabel(centralWidget);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(280, 350, 72, 15));
        label_13->setAlignment(Qt::AlignCenter);
        cartYp = new QPushButton(centralWidget);
        cartYp->setObjectName(QString::fromUtf8("cartYp"));
        cartYp->setGeometry(QRect(280, 410, 31, 24));
        cartRun = new QPushButton(centralWidget);
        cartRun->setObjectName(QString::fromUtf8("cartRun"));
        cartRun->setGeometry(QRect(300, 560, 93, 41));
        cartThetap = new QPushButton(centralWidget);
        cartThetap->setObjectName(QString::fromUtf8("cartThetap"));
        cartThetap->setGeometry(QRect(580, 410, 31, 24));
        lineV = new QLineEdit(centralWidget);
        lineV->setObjectName(QString::fromUtf8("lineV"));
        lineV->setGeometry(QRect(750, 670, 71, 31));
        label_27 = new QLabel(centralWidget);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(80, 814, 72, 21));
        label_20 = new QLabel(centralWidget);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(210, 560, 72, 20));
        label_20->setAlignment(Qt::AlignCenter);
        cyclePsi2 = new QLineEdit(centralWidget);
        cyclePsi2->setObjectName(QString::fromUtf8("cyclePsi2"));
        cyclePsi2->setGeometry(QRect(450, 810, 71, 31));
        label_31 = new QLabel(centralWidget);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(450, 650, 72, 15));
        label_31->setAlignment(Qt::AlignCenter);
        label_40 = new QLabel(centralWidget);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(750, 790, 72, 21));
        label_40->setAlignment(Qt::AlignCenter);
        label_8 = new QLabel(centralWidget);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(680, 190, 72, 15));
        label_8->setAlignment(Qt::AlignCenter);
        label_24 = new QLabel(centralWidget);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(80, 680, 72, 15));
        theta2p = new QPushButton(centralWidget);
        theta2p->setObjectName(QString::fromUtf8("theta2p"));
        theta2p->setGeometry(QRect(280, 260, 31, 24));
        label_17 = new QLabel(centralWidget);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(680, 350, 72, 15));
        label_17->setAlignment(Qt::AlignCenter);
        cartZp = new QPushButton(centralWidget);
        cartZp->setObjectName(QString::fromUtf8("cartZp"));
        cartZp->setGeometry(QRect(380, 410, 31, 24));
        cartXp = new QPushButton(centralWidget);
        cartXp->setObjectName(QString::fromUtf8("cartXp"));
        cartXp->setGeometry(QRect(180, 410, 31, 24));
        label_16 = new QLabel(centralWidget);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(580, 350, 72, 15));
        label_16->setAlignment(Qt::AlignCenter);
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(480, 190, 72, 15));
        label_6->setAlignment(Qt::AlignCenter);
        theta4p = new QPushButton(centralWidget);
        theta4p->setObjectName(QString::fromUtf8("theta4p"));
        theta4p->setGeometry(QRect(480, 260, 31, 24));
        label_44 = new QLabel(centralWidget);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(510, 450, 72, 20));
        label_44->setAlignment(Qt::AlignCenter);
        label_22 = new QLabel(centralWidget);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(70, 300, 151, 31));
        label_22->setFont(font);
        theta5m = new QPushButton(centralWidget);
        theta5m->setObjectName(QString::fromUtf8("theta5m"));
        theta5m->setGeometry(QRect(620, 260, 31, 24));
        label_23 = new QLabel(centralWidget);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(80, 620, 151, 31));
        label_23->setFont(font);
        cycleTheta2 = new QLineEdit(centralWidget);
        cycleTheta2->setObjectName(QString::fromUtf8("cycleTheta2"));
        cycleTheta2->setGeometry(QRect(550, 810, 71, 31));
        cartDisplay = new QTextBrowser(centralWidget);
        cartDisplay->setObjectName(QString::fromUtf8("cartDisplay"));
        cartDisplay->setGeometry(QRect(510, 470, 421, 131));
        cartDisplay->setReadOnly(true);
        theta5 = new QTextBrowser(centralWidget);
        theta5->setObjectName(QString::fromUtf8("theta5"));
        theta5->setGeometry(QRect(580, 210, 71, 31));
        theta5p = new QPushButton(centralWidget);
        theta5p->setObjectName(QString::fromUtf8("theta5p"));
        theta5p->setGeometry(QRect(580, 260, 31, 24));
        theta4 = new QTextBrowser(centralWidget);
        theta4->setObjectName(QString::fromUtf8("theta4"));
        theta4->setGeometry(QRect(480, 210, 71, 31));
        label_11 = new QLabel(centralWidget);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(140, 374, 72, 21));
        theta3 = new QTextBrowser(centralWidget);
        theta3->setObjectName(QString::fromUtf8("theta3"));
        theta3->setGeometry(QRect(380, 210, 71, 31));
        linePsi = new QLineEdit(centralWidget);
        linePsi->setObjectName(QString::fromUtf8("linePsi"));
        linePsi->setGeometry(QRect(450, 670, 71, 31));
        cycleY1 = new QLineEdit(centralWidget);
        cycleY1->setObjectName(QString::fromUtf8("cycleY1"));
        cycleY1->setGeometry(QRect(250, 760, 71, 31));
        cartYm = new QPushButton(centralWidget);
        cartYm->setObjectName(QString::fromUtf8("cartYm"));
        cartYm->setGeometry(QRect(320, 410, 31, 24));
        theta6 = new QTextBrowser(centralWidget);
        theta6->setObjectName(QString::fromUtf8("theta6"));
        theta6->setGeometry(QRect(680, 210, 71, 31));
        clearSysState = new QPushButton(centralWidget);
        clearSysState->setObjectName(QString::fromUtf8("clearSysState"));
        clearSysState->setGeometry(QRect(860, 160, 93, 41));
        lineRun = new QPushButton(centralWidget);
        lineRun->setObjectName(QString::fromUtf8("lineRun"));
        lineRun->setGeometry(QRect(840, 640, 91, 41));
        label_32 = new QLabel(centralWidget);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(350, 650, 72, 15));
        label_32->setAlignment(Qt::AlignCenter);
        label_18 = new QLabel(centralWidget);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(140, 410, 31, 21));
        label_41 = new QLabel(centralWidget);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(350, 790, 72, 15));
        label_41->setAlignment(Qt::AlignCenter);
        cycleX2 = new QLineEdit(centralWidget);
        cycleX2->setObjectName(QString::fromUtf8("cycleX2"));
        cycleX2->setGeometry(QRect(150, 810, 71, 31));
        label_33 = new QLabel(centralWidget);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(650, 650, 72, 15));
        label_33->setAlignment(Qt::AlignCenter);
        label_30 = new QLabel(centralWidget);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(250, 650, 72, 15));
        label_30->setAlignment(Qt::AlignCenter);
        label_10 = new QLabel(centralWidget);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(180, 10, 131, 31));
        label_10->setFont(font);
        connect = new QPushButton(centralWidget);
        connect->setObjectName(QString::fromUtf8("connect"));
        connect->setGeometry(QRect(290, 50, 91, 41));
        close = new QPushButton(centralWidget);
        close->setObjectName(QString::fromUtf8("close"));
        close->setGeometry(QRect(290, 100, 91, 41));
        label_34 = new QLabel(centralWidget);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(70, 10, 131, 31));
        label_34->setFont(font);
        enable = new QPushButton(centralWidget);
        enable->setObjectName(QString::fromUtf8("enable"));
        enable->setGeometry(QRect(390, 50, 91, 41));
        stop = new QPushButton(centralWidget);
        stop->setObjectName(QString::fromUtf8("stop"));
        stop->setGeometry(QRect(390, 100, 91, 41));
        label_37 = new QLabel(centralWidget);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(178, 70, 101, 20));
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(label_37->sizePolicy().hasHeightForWidth());
        label_37->setSizePolicy(sizePolicy);
        label_37->setAlignment(Qt::AlignCenter);
        CANCom = new QComboBox(centralWidget);
        CANCom->addItem(QString());
        CANCom->addItem(QString());
        CANCom->setObjectName(QString::fromUtf8("CANCom"));
        CANCom->setGeometry(QRect(180, 100, 101, 23));
        label_46 = new QLabel(centralWidget);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(180, 120, 101, 16));
        label_46->setAlignment(Qt::AlignCenter);
        baundRate = new QComboBox(centralWidget);
        baundRate->addItem(QString());
        baundRate->addItem(QString());
        baundRate->setObjectName(QString::fromUtf8("baundRate"));
        baundRate->setGeometry(QRect(180, 50, 101, 23));
        systermState_2 = new QTextBrowser(centralWidget);
        systermState_2->setObjectName(QString::fromUtf8("systermState_2"));
        systermState_2->setEnabled(false);
        systermState_2->setGeometry(QRect(170, 10, 321, 141));
        systermState_2->setFrameShadow(QFrame::Sunken);
        systermState_2->setReadOnly(true);
        systermState_3 = new QTextBrowser(centralWidget);
        systermState_3->setObjectName(QString::fromUtf8("systermState_3"));
        systermState_3->setEnabled(false);
        systermState_3->setGeometry(QRect(50, 10, 121, 141));
        systermState_3->setReadOnly(true);
        systermState_4 = new QTextBrowser(centralWidget);
        systermState_4->setObjectName(QString::fromUtf8("systermState_4"));
        systermState_4->setEnabled(false);
        systermState_4->setGeometry(QRect(50, 150, 711, 141));
        systermState_4->setReadOnly(true);
        systermState_5 = new QTextBrowser(centralWidget);
        systermState_5->setObjectName(QString::fromUtf8("systermState_5"));
        systermState_5->setEnabled(false);
        systermState_5->setGeometry(QRect(50, 290, 711, 151));
        systermState_5->setReadOnly(true);
        systermState_6 = new QTextBrowser(centralWidget);
        systermState_6->setObjectName(QString::fromUtf8("systermState_6"));
        systermState_6->setEnabled(false);
        systermState_6->setGeometry(QRect(50, 440, 911, 171));
        systermState_6->setReadOnly(true);
        systermState_7 = new QTextBrowser(centralWidget);
        systermState_7->setObjectName(QString::fromUtf8("systermState_7"));
        systermState_7->setEnabled(false);
        systermState_7->setGeometry(QRect(50, 610, 911, 101));
        systermState_7->setReadOnly(true);
        systermState_8 = new QTextBrowser(centralWidget);
        systermState_8->setObjectName(QString::fromUtf8("systermState_8"));
        systermState_8->setEnabled(false);
        systermState_8->setGeometry(QRect(50, 710, 911, 141));
        systermState_8->setReadOnly(true);
        MainWindow->setCentralWidget(centralWidget);
        systermState_8->raise();
        systermState_7->raise();
        systermState_6->raise();
        systermState_5->raise();
        systermState_4->raise();
        systermState_3->raise();
        systermState_2->raise();
        cartPsip->raise();
        initialize->raise();
        cycleTheta1->raise();
        record->raise();
        label_5->raise();
        cartThetam->raise();
        label_14->raise();
        cycleZ1->raise();
        label_19->raise();
        label_4->raise();
        label_43->raise();
        theta2->raise();
        clear->raise();
        cartPhip->raise();
        label_28->raise();
        cartZm->raise();
        cartPhim->raise();
        label_39->raise();
        linePhi->raise();
        cartPhi->raise();
        label_26->raise();
        theta1->raise();
        label_12->raise();
        theta1p->raise();
        cartZ->raise();
        label_9->raise();
        label_25->raise();
        label_29->raise();
        cartY->raise();
        theta3m->raise();
        cyclePhi2->raise();
        label_45->raise();
        cartV->raise();
        theta3p->raise();
        cyclePhi1->raise();
        label_3->raise();
        cyclePsi1->raise();
        cartPsim->raise();
        goToZero->raise();
        cartPsi->raise();
        cartXm->raise();
        label_42->raise();
        theta6m->raise();
        cycleX1->raise();
        label->raise();
        cartTheta->raise();
        theta2m->raise();
        label_2->raise();
        label_38->raise();
        lineZ->raise();
        cycleY2->raise();
        cycleRun->raise();
        lineTheta->raise();
        cartX->raise();
        cartCNT->raise();
        cycleV->raise();
        systermState->raise();
        label_7->raise();
        label_36->raise();
        theta1m->raise();
        theta4m->raise();
        lineX->raise();
        label_21->raise();
        label_15->raise();
        lineY->raise();
        label_35->raise();
        cycleZ2->raise();
        theta6p->raise();
        label_13->raise();
        cartYp->raise();
        cartRun->raise();
        cartThetap->raise();
        lineV->raise();
        label_27->raise();
        label_20->raise();
        cyclePsi2->raise();
        label_31->raise();
        label_40->raise();
        label_8->raise();
        label_24->raise();
        theta2p->raise();
        label_17->raise();
        cartZp->raise();
        cartXp->raise();
        label_16->raise();
        label_6->raise();
        theta4p->raise();
        label_44->raise();
        label_22->raise();
        theta5m->raise();
        label_23->raise();
        cycleTheta2->raise();
        cartDisplay->raise();
        theta5->raise();
        theta5p->raise();
        theta4->raise();
        label_11->raise();
        theta3->raise();
        linePsi->raise();
        cycleY1->raise();
        cartYm->raise();
        theta6->raise();
        clearSysState->raise();
        lineRun->raise();
        label_32->raise();
        label_18->raise();
        label_41->raise();
        cycleX2->raise();
        label_33->raise();
        label_30->raise();
        label_10->raise();
        connect->raise();
        close->raise();
        label_34->raise();
        enable->raise();
        stop->raise();
        label_37->raise();
        CANCom->raise();
        label_46->raise();
        baundRate->raise();
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 988, 25));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        cartPsip->setText(QApplication::translate("MainWindow", "+", nullptr));
        initialize->setText(QApplication::translate("MainWindow", "\345\210\235\345\247\213\345\214\226", nullptr));
        record->setText(QApplication::translate("MainWindow", "\350\256\260  \345\275\225", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "\316\2703", nullptr));
        cartThetam->setText(QApplication::translate("MainWindow", "-", nullptr));
        label_14->setText(QApplication::translate("MainWindow", "z", nullptr));
        label_19->setText(QApplication::translate("MainWindow", "\351\200\237\345\272\246", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "\316\2702", nullptr));
        label_43->setText(QApplication::translate("MainWindow", "y", nullptr));
        clear->setText(QApplication::translate("MainWindow", "\346\270\205  \351\231\244", nullptr));
        cartPhip->setText(QApplication::translate("MainWindow", "+", nullptr));
        label_28->setText(QApplication::translate("MainWindow", "\350\277\236\347\273\255\350\275\250\350\277\271\346\216\247\345\210\266", nullptr));
        cartZm->setText(QApplication::translate("MainWindow", "-", nullptr));
        cartPhim->setText(QApplication::translate("MainWindow", "-", nullptr));
        label_39->setText(QApplication::translate("MainWindow", "\317\210(x)", nullptr));
        label_26->setText(QApplication::translate("MainWindow", "\350\275\250\350\277\271\347\202\2711", nullptr));
        label_12->setText(QApplication::translate("MainWindow", "x", nullptr));
        theta1p->setText(QApplication::translate("MainWindow", "+", nullptr));
        label_9->setText(QApplication::translate("MainWindow", "\347\202\271\345\212\250", nullptr));
        label_25->setText(QApplication::translate("MainWindow", "\345\234\206\345\274\247\350\275\250\350\277\271\346\216\247\345\210\266", nullptr));
        label_29->setText(QApplication::translate("MainWindow", "x", nullptr));
        theta3m->setText(QApplication::translate("MainWindow", "-", nullptr));
        label_45->setText(QApplication::translate("MainWindow", "\347\263\273\347\273\237\347\212\266\346\200\201", nullptr));
        theta3p->setText(QApplication::translate("MainWindow", "+", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "\316\2701", nullptr));
        cartPsim->setText(QApplication::translate("MainWindow", "-", nullptr));
        goToZero->setText(QApplication::translate("MainWindow", "\345\233\236  \351\233\266", nullptr));
        cartXm->setText(QApplication::translate("MainWindow", "-", nullptr));
        label_42->setText(QApplication::translate("MainWindow", "\316\270(y)", nullptr));
        theta6m->setText(QApplication::translate("MainWindow", "-", nullptr));
        label->setText(QApplication::translate("MainWindow", "\345\205\263\350\212\202\347\251\272\351\227\264\346\216\247\345\210\266", nullptr));
        theta2m->setText(QApplication::translate("MainWindow", "-", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "\346\230\276\347\244\272", nullptr));
        label_38->setText(QApplication::translate("MainWindow", "x", nullptr));
        cycleRun->setText(QApplication::translate("MainWindow", "\350\277\220  \350\241\214", nullptr));
        label_7->setText(QApplication::translate("MainWindow", "\316\2705", nullptr));
        label_36->setText(QApplication::translate("MainWindow", "\317\206(z)", nullptr));
        theta1m->setText(QApplication::translate("MainWindow", "-", nullptr));
        theta4m->setText(QApplication::translate("MainWindow", "-", nullptr));
        label_21->setText(QApplication::translate("MainWindow", "\316\270(y)", nullptr));
        label_15->setText(QApplication::translate("MainWindow", "\317\210(x)", nullptr));
        label_35->setText(QApplication::translate("MainWindow", "\351\200\237\345\272\246", nullptr));
        theta6p->setText(QApplication::translate("MainWindow", "+", nullptr));
        label_13->setText(QApplication::translate("MainWindow", "y", nullptr));
        cartYp->setText(QApplication::translate("MainWindow", "+", nullptr));
        cartRun->setText(QApplication::translate("MainWindow", "\350\277\220  \350\241\214", nullptr));
        cartThetap->setText(QApplication::translate("MainWindow", "+", nullptr));
        label_27->setText(QApplication::translate("MainWindow", "\350\275\250\350\277\271\347\202\2712", nullptr));
        label_20->setText(QApplication::translate("MainWindow", "CNT", nullptr));
        label_31->setText(QApplication::translate("MainWindow", "\317\210(x)", nullptr));
        label_40->setText(QApplication::translate("MainWindow", "\351\200\237\345\272\246", nullptr));
        label_8->setText(QApplication::translate("MainWindow", "\316\2706", nullptr));
        label_24->setText(QApplication::translate("MainWindow", "\350\275\250\350\277\271\347\202\271", nullptr));
        theta2p->setText(QApplication::translate("MainWindow", "+", nullptr));
        label_17->setText(QApplication::translate("MainWindow", "\317\206(z)", nullptr));
        cartZp->setText(QApplication::translate("MainWindow", "+", nullptr));
        cartXp->setText(QApplication::translate("MainWindow", "+", nullptr));
        label_16->setText(QApplication::translate("MainWindow", "\316\270(y)", nullptr));
        label_6->setText(QApplication::translate("MainWindow", "\316\2704", nullptr));
        theta4p->setText(QApplication::translate("MainWindow", "+", nullptr));
        label_44->setText(QApplication::translate("MainWindow", "\350\275\250\350\277\271\346\230\276\347\244\272", nullptr));
        label_22->setText(QApplication::translate("MainWindow", "\347\254\233\345\215\241\345\260\224\347\251\272\351\227\264\346\216\247\345\210\266", nullptr));
        theta5m->setText(QApplication::translate("MainWindow", "-", nullptr));
        label_23->setText(QApplication::translate("MainWindow", "\347\233\264\347\272\277\350\275\250\350\277\271\346\216\247\345\210\266", nullptr));
        theta5p->setText(QApplication::translate("MainWindow", "+", nullptr));
        label_11->setText(QApplication::translate("MainWindow", "\346\230\276\347\244\272", nullptr));
        cartYm->setText(QApplication::translate("MainWindow", "-", nullptr));
        clearSysState->setText(QApplication::translate("MainWindow", "\346\270\205  \351\231\244", nullptr));
        lineRun->setText(QApplication::translate("MainWindow", "\350\277\220  \350\241\214", nullptr));
        label_32->setText(QApplication::translate("MainWindow", "z", nullptr));
        label_18->setText(QApplication::translate("MainWindow", "\347\202\271\345\212\250", nullptr));
        label_41->setText(QApplication::translate("MainWindow", "z", nullptr));
        label_33->setText(QApplication::translate("MainWindow", "\317\206(z)", nullptr));
        label_30->setText(QApplication::translate("MainWindow", "y", nullptr));
        label_10->setText(QApplication::translate("MainWindow", "CANOpen\351\200\232\344\277\241", nullptr));
        connect->setText(QApplication::translate("MainWindow", "\350\277\236\346\216\245", nullptr));
        close->setText(QApplication::translate("MainWindow", "\346\226\255\345\274\200", nullptr));
        label_34->setText(QApplication::translate("MainWindow", "\347\263\273\347\273\237\345\221\275\344\273\244", nullptr));
        enable->setText(QApplication::translate("MainWindow", "\344\275\277\350\203\275", nullptr));
        stop->setText(QApplication::translate("MainWindow", "\345\201\234\346\255\242", nullptr));
        label_37->setText(QApplication::translate("MainWindow", "\346\263\242\347\211\271\347\216\207", nullptr));
        CANCom->setItemText(0, QApplication::translate("MainWindow", "0", nullptr));
        CANCom->setItemText(1, QApplication::translate("MainWindow", "1", nullptr));

        label_46->setText(QApplication::translate("MainWindow", "\351\200\232\351\201\223", nullptr));
        baundRate->setItemText(0, QApplication::translate("MainWindow", "1000Kbps", nullptr));
        baundRate->setItemText(1, QApplication::translate("MainWindow", "500Kbps", nullptr));

    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
